-- Limited edition posters from public/assests/poster (₹299 sale, ₹600 MRP).
-- Run in Supabase SQL Editor after products table + slug unique exist.
-- Safe to re-run: upserts on slug.

INSERT INTO public.products (
  name,
  description,
  price,
  original_price,
  category,
  image_url,
  model_url,
  slug,
  stock_quantity,
  is_featured,
  rating,
  rating_count
)
VALUES
  (
    'Limited edition poster (59190d06…) — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/59190d06bf7cf9dd960890942a1d094f.jpg',
    NULL,
    'le-poster-59190d06bf7cf9dd960890942a1d094f',
    100,
    false,
    4.6,
    128
  ),
  (
    'Limited edition poster (64997994…) — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/649979948a46121e53349c791d4e2a83.jpg',
    NULL,
    'le-poster-649979948a46121e53349c791d4e2a83',
    100,
    false,
    4.6,
    128
  ),
  (
    'Loffy — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/loffy.jpg',
    NULL,
    'le-poster-loffy',
    100,
    false,
    4.6,
    128
  ),
  (
    'Luffy 3 — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/luffy3.jpg',
    NULL,
    'le-poster-luffy3',
    100,
    false,
    4.6,
    128
  ),
  (
    'Naruto — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/naruto.jpg',
    NULL,
    'le-poster-naruto',
    100,
    false,
    4.6,
    128
  ),
  (
    'Naruto 2 — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/naruto2.jpg',
    NULL,
    'le-poster-naruto2',
    100,
    false,
    4.6,
    128
  ),
  (
    'Zoro — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/zoro.jpg',
    NULL,
    'le-poster-zoro',
    100,
    false,
    4.6,
    128
  ),
  (
    'Zoro 1 — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/zoro1.png',
    NULL,
    'le-poster-zoro1',
    100,
    false,
    4.6,
    128
  ),
  (
    'Zoro 3 — Limited edition',
    'Premium limited edition anime poster print. High-quality art print — gallery-ready. MRP ₹600; special launch price ₹299.',
    29900,
    60000,
    'limited_edition',
    '/assests/poster/zoro3.jpg',
    NULL,
    'le-poster-zoro3',
    100,
    false,
    4.6,
    128
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category = EXCLUDED.category,
  image_url = EXCLUDED.image_url,
  model_url = EXCLUDED.model_url,
  stock_quantity = EXCLUDED.stock_quantity,
  is_featured = EXCLUDED.is_featured,
  rating = EXCLUDED.rating,
  rating_count = EXCLUDED.rating_count;
